const projectData = [
  {
    id: '1',
    category: 'all',
    title: '慶嵩企業股份有限公司',
    image: './image/chinshong.jpg',
    demoUrl: 'http://jlwork.com/2007_chinshong/web/',
    duration: '1 month',
    role: 'Designer、Front-End',
    skill: ['Sass', 'jQuery'],
    sourceCodeUrl: '',
  },
  {
    id: '2',
    category: 'all',
    title: '晶相光電股份有限公司',
    image: './image/soinc.jpg',
    demoUrl: 'https://www.soinc.com.tw/',
    duration: '1 month',
    role: 'Designer、Front-End',
    skill: ['Sass', 'jQuery'],
    sourceCodeUrl: '',
  },
  {
    id: '3',
    category: 'all',
    title: 'React-Redux Blog',
    image: './image/blog.jpg',
    demoUrl: 'https://milyzoo.github.io/lidemy-react-redux-blog/',
    duration: '1 month',
    role: 'Designer、Front-End',
    skill: [
      '以 React 開發，搭配 Redux 及 React-router',
      '使用 function component 並搭配 Hooks',
      '使用 Redux + Redux Toolkit 管理組件狀態',
      '使用 React-router 處理前端路由',
      '支援 RWD，使用 styled-components 進行排版',
    ],
    sourceCodeUrl: 'https://github.com/milyzoo/lidemy-react-redux-blog',
  },
  {
    id: '4',
    category: 'all',
    title: 'NiMin Chat',
    image: './image/chat.png',
    demoUrl: 'https://milyzoo.github.io/nimin-chat/',
    duration: '2 weeek',
    role: 'Designer、Front-End',
    skill: [
      '以 React 開發，使用 function component 並搭配 Hooks API',
      '使用 React Context 管理組件狀態',
      '使用 Firebase Realtime Database 儲存資料，並即時同步至所連線的用戶端',
      '使用 React-router 處理前端路由',
      '支援 RWD，使用 styled-components 進行排版',
    ],
    sourceCodeUrl: 'https://github.com/milyzoo/nimin-chat',
  }
]